### DISCUSSION TITLE
Configuration options for ``mypy``

### DISCUSSION THREAD

**Discussion by alexdewar** [ImperialCollegeLondon/virtual_rainforest#60] [General]
As discussed in the meeting, there are various options that one can enable in ``mypy``. The options can be added to a section in ``pyproject.toml`` like so:
```toml
[tool.mypy]
ignore_missing_imports = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
```

Those options are ones that I'm using for another project and they may not all suit you. The one that I'd strongly recommend is ``ignore_missing_imports = true``. It stops ``mypy`` from giving errors when types for external libraries are unknown (as is very commonly the case!). The other options essentially just make type annotations mandatory everywhere -- otherwise ``mypy`` will only check that annotations are correct, not whether they are present.
