### ISSUE TITLE
Allow for easily setting the output path for simulation files

### ISSUE THREAD

**Issue by alexdewar** [ImperialCollegeLondon/virtual_rainforest#271]
Currently, VR produces a number of output files for a simulation and allows the user to choose the paths for these files like so:

```toml
[core.data_output_options]
save_initial_state = true
save_continuous_data = true
save_final_state = true
out_path_initial = "./initial_state.nc"
out_folder_continuous = "."
continuous_file_name = "all_continuous_data"
out_path_final = "./final_state.nc"
```

(These are just the default values.)

In addition to these, there is also the path to the merged config file, which is not settable via a parameter (see #270). Note that in order to make sure that all files are output to the same folder, the user has to set a bunch of paths explicitly. Also note that `continuous_file_name` is unique in a) not including a path (because the value of `out_folder_continuous` is used) and b) not including a file extension (`.nc` is used). In future, in the event that new output file types are added to VR, the user will presumably have to supply the whole paths for these too. I'm using different output folders for different simulations as part of my work on #239 and I'm finding the current mechanism rather cumbersome.

I propose that we make the output folder a separate parameter, so that the user can just set this once in order to get all the output files in one place. Furthermore, I suggest that we let the user choose the file names for the initial and final state files, but not the whole path. (We should also probably just put `all_continuous_data.nc` in the output folder too.) This means users would lose the ability to put the initial and final state files into different folders (for example), but this is a rather peculiar thing to want to do in any case, so I don't think it's much of a loss. We *may* want to keep `out_folder_continuous` as a separate option, in case e.g. the user wants to write these files to `/tmp`, but in any case it should probably default to the common output folder too (otherwise you get file conflicts if you're trying to run multiple simulations from the same folder at the same time).

What does everyone think?
