### ISSUE TITLE
Add constant value setting for data elements in configuration.

### ISSUE THREAD

**Issue by davidorme** [ImperialCollegeLondon/virtual_rainforest#677]
We need a system that does something like:

```toml
[data.variable]
var_name = "precipitation"
constant = 4
```

I have a feeling that there is a sketch in a discussion somewhere!
