### ISSUE TITLE
Documentation for static model

### ISSUE THREAD

**Issue by sallymatson** [ImperialCollegeLondon/virtual_rainforest#686]
@vgro and I have discussed some initial documentation of the static model for users, with the example data and pypi package. 

I will work on the description of the model, purpose, and go through how to set it up in the config. 

@vgro will add a short example of how to make some tweaks to see results using static.

**Comment by hrlai** [comment]
Hi there, is this going to change the instruction on [this page](https://virtual-ecosystem.readthedocs.io/en/latest/using_the_ve/configuration/config.html#static-models)? I am trying to run a soil-only simulation, but the following config does not seem to work:
```
[core]
[hydrology.depends]
init = ['plants']
update = ['plants', 'abiotic_simple']
static = true
[abiotic_simple]
static = true
[animals]
static = true
[litter.depends]
update = ['hydrology', 'abiotic_simple']
static = true
[soil.depends]
init = ['hydrology', 'abiotic_simple']
update = ['hydrology', 'abiotic_simple']
```

I got the following errors:
```
[ERROR] - config - validate_config(507) - Configuration error in ['animals']: Additional properties are not allowed ('static' was unexpected)
[ERROR] - config - validate_config(507) - Configuration error in ['hydrology', 'depends']: Additional properties are not allowed ('static' was unexpected)
[ERROR] - config - validate_config(507) - Configuration error in ['abiotic_simple']: Additional properties are not allowed ('static' was unexpected)
[ERROR] - config - validate_config(507) - Configuration error in ['litter', 'depends']: Additional properties are not allowed ('static' was unexpected)
```

Did I miss something? Thanks.

**Comment by davidorme** [comment]
Which version are you running? All of those `depends` sections are outdated and should be removed and `static` should recognised.

**Comment by davidorme** [comment]
Also note that you're unintentionally nesting `static` inside `depends` in a couple of places. It should be `model_name.static` not `model_name.depends.static`. Like this:

```toml
[core]
[hydrology]
static = true
[hydrology.depends]
init = ['plants']
update = ['plants', 'abiotic_simple']
[abiotic_simple]
static = true
[animals]
static = true
[litter]
static = true
[litter.depends]
update = ['hydrology', 'abiotic_simple']
[soil.depends]
init = ['hydrology', 'abiotic_simple']
update = ['hydrology', 'abiotic_simple']
```
