### ISSUE TITLE
We don't currently support python `3.13`

### ISSUE THREAD

**Issue by jacobcook1995** [ImperialCollegeLondon/virtual_rainforest#722]
We don't currently support `python 3.13`. This is a problem as windows users being prompted to install python get pointed to `3.13` as a default which then leaves them unable to install the `virtual_ecosystem` package. I can't see any good reason for us not to support `3.13` so I think we should add it as a supported version

**Comment by davidorme** [comment]
Eh? `poetry` has: `python = ">=3.10,<3.13" `

And our CI testing has:

```yaml
  test:
    needs: qa
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ "3.10", "3.11", "3.12"]
```
